### ISSUE TITLE
Faculty message not visible in light mode

### ISSUE THREAD

**Issue by rahulsingh2312** [tcet-opensource/iste-website#14]
![Screenshot (227)](https://github.com/tcet-opensource/iste-website/assets/111289008/272b4847-a9bb-4307-9718-e2caf65ad7bd)

**Comment by rahulsingh2312** [comment]
Assign this issue to me!

**Comment by demonkillerr** [comment]
create a branch based on this issue so that it can be tracked

**Comment by rizzabh** [comment]
Not just this text but there are some other texts too.
