### ISSUE TITLE
Navbar button is not working 

### ISSUE THREAD

**Issue by rahulsingh2312** [tcet-opensource/iste-website#17]
when u press on about/events its not working pink color stays on home only
![Screenshot (232)](https://github.com/tcet-opensource/iste-website/assets/111289008/9c6a0a68-8826-48fe-8cb6-f8bbd1a73c34)

**Comment by rahulsingh2312** [comment]
assign this issue to me

**Comment by Bhumi1685** [comment]
Assign it to me

**Comment by KhushiTiwarii** [comment]
Assign it to me
