### ISSUE TITLE
Restructure directories

### ISSUE THREAD

**Issue by demonkillerr** [tcet-opensource/iste-website#18]
This issue tracks the efforts to restructure the entire ISTE Website CodeBase so that all pages that are **NOT** index, have a proper trailing URL.

#### Current behavior:
Going on the `events` page for example shows this url: `https://iste.tcetmumbai.in/events.html`

#### Expected behavior:
Going on the events page should show this URL: `https://iste.tcetmumbai.in/events/`

**Comment by rahulsingh2312** [comment]
assign this to me 🙏
