### ISSUE TITLE
[Asset Optimization]: Implement Lossless Image Optimization for Improved Website Performance & more

### ISSUE THREAD

**Issue by prathikshetty2002** [tcet-opensource/iste-website#23]
## Expected Behavior

- [ ] Faster website loading times, resulting in improved user experience.
- [ ] Reduced bandwidth consumption, leading to cost savings and improved performance on low-speed networks.
- [ ] Enhanced SEO rankings due to faster page load times.
- [ ] Consistent visual quality across all images.

### Lighthouse report
![image](https://github.com/tcet-opensource/iste-website/assets/63772910/33a557f3-db1a-456c-a378-e2b504193b4f)

### Resource loading 
![iste img opt](https://github.com/tcet-opensource/iste-website/assets/63772910/b52bf6a7-d00e-4a50-990a-4cad2b1fa995)

![image](https://github.com/tcet-opensource/iste-website/assets/63772910/a061c2b3-2bf9-4e90-838e-92160b3513a0)

## Possible Solution
- [ ] Resize images properly in a lossless manner
- [ ] Serve images in next-gen format
- [ ] Eliminate render-blocking resources
- [ ] Efficiently encode images

## Context

Optimizing image assets is a critical step to ensure our website's fast loading times and optimal user experience. Currently, our images could benefit from lossless compression techniques to reduce their file sizes without compromising visual quality. This issue is dedicated to implementing lossless image optimization across the website, which will contribute to faster load times, reduced bandwidth consumption, and overall improved performance.

## Your Environment

* Version used: latest
* Browser Name and version: Using Chromium 115.0.0.0 with devtools
* Operating System and version (desktop or mobile): Emulated Moto G Power with Lighthouse 10.2.
* Slow 4G throttling

**Comment by aman-prajapati05** [comment]
Assign this to me
